global:
   # Каждые 5 секунд опрос метрик. Если в течение 10с у него не получится их собрать, то будет прерывание по таймауту
  scrape_interval: 30s
  scrape_timeout: 15s


scrape_configs:
  # имя сборщика
  - job_name: 'aiogram_bot'
    metrics_path: /metrics
    static_configs:
      - targets: ['aiogram-bot:8000']
