{
 "title": "Dashboard1",
 "time": { "from": "2025-01-31T11:33:46.690Z", "to": "2025-01-31T11:38:46.690Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS(messages)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(messages_count_total{job=\"aiogram_bot\"}[5m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Среднее время обработки сообщения за 1м",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(handler_duration_seconds_sum[1m])) / avg(rate(handler_duration_seconds_count[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90-й процентиль (p90) времени обработки запросов",
   "type": "timeseries",
   "description": "90-й процентиль (p90) времени обработки сообщения",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(handler_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}