{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TotalMemory",
    "query": {
     "query": "query_result(node_memory_MemTotal_bytes)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (cpu) * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Uses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Использвано памяти"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Всего памяти" }
   ]
  },
  {
   "title": "SWAP Uses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes -  node_memory_SwapFree_bytes) \n",
     "legendFormat": "Использвано памяти"
    },
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "Всего памяти" }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "All Containers uses RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ALL conteiners usage RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "RPM (Messages)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(aiogram_errors_total[1m])) * 60 or vector(0)",
     "legendFormat": "Error"
    },
    {
     "expr": "rate(aiogram_rps_total[1m]) * 60",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Время ответа на сообщение",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "\nrate(aiogram_response_duration_seconds_sum[5m]) / rate(aiogram_response_duration_seconds_count[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(increase(aiogram_errors_total[1m])) by (error_type) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}