from decouple import config
import itertools

BOT_TOKEN = config("TELEGRAM_BOT_TOKEN")
YOOKASSA_PAYMENT_TOKEN = config("YOOKASSA_PAYMENT_TOKEN")
API_KEY1 = config("OPENAI_API_KEY")
API_KEY2 = config("OPENAI_API_KEY2")
API_KEY3 = config("OPENAI_API_KEY3")
API_KEY4 = config("OPENAI_API_KEY4")
API_KEY5 = config("OPENAI_API_KEY5")
API_KEY6 = config("OPENAI_API_KEY6")
API_KEY7 = config("OPENAI_API_KEY7")
API_KEY8 = config("OPENAI_API_KEY8")
OPENAI_KEYS = itertools.cycle((API_KEY1, API_KEY2, API_KEY3, API_KEY4, API_KEY5, API_KEY6, API_KEY7, API_KEY8))
