name: Auto PR Title on Merge

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
    paths:
      - 'dev/**'  # Трекаем изменения только из ветки dev

jobs:
  auto-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Increment version for next release
        id: increment_version
        run: |
          VERSION="${{ env.tag }}"
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEXT_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "Next version: v$NEXT_VERSION"
          echo "next_version=v$NEXT_VERSION" >> $GITHUB_ENV

      - name: Update PR title
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          NEW_TITLE="Release ${{ env.next_version }}"
          echo "New PR title: $NEW_TITLE"
          
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
            -d "{\"title\": \"$NEW_TITLE\"}"
