name: Deploy to Server

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  # Запуск вручную из GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/ChatGPT_Telegram_Bot
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
            docker image prune -f