name: Deploy to Server

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod  # Проверки при PR в prod

jobs:
  test:
      name: Run Tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Run Linter & Tests
          run: |
            # TODO
            # pytest


  deploy:
    name: Deploy to VPS
    needs: test
    if: github.event_name == 'push'  # Деплой только на push в prod!
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USER  }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e  # Остановка при ошибке
            cd /root/ChatGPT_Telegram_Bot
            git checkout prod
            git pull origin prod
            docker compose pull  # Загружаем свежие образы
            docker compose up --build -d  # Пересобираем и запускаем
            docker system prune -f  # Очищаем старые образы и контейнеры (опционально)


  tag_release:
    name: Tag new release
    needs: deploy  # Тегируем только после успешного деплоя
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USER  }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e  # Остановка при ошибке
            cd /root/ChatGPT_Telegram_Bot
            # Получаем последний тег (например, v1.4.4)
            LATEST_TAG=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
            
            if [[ -z "$LATEST_TAG" ]]; then
              NEW_TAG="v1.0.0"  # Если тега нет, начинаем с v1.0.0
            else
              # Увеличиваем патч-версию (v1.4.4 -> v1.4.5)
              IFS='.' read -r -a PARTS <<< "${LATEST_TAG:1}"  # Убираем "v" и разбиваем на массив
              NEW_TAG="v${PARTS[0]}.${PARTS[1]}.$((PARTS[2] + 1))"
            fi
            
            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
            echo "Latest tag: $LATEST_TAG"
            echo "Next tag: $NEW_TAG"

      - name: Create and push new tag
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USER  }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git tag $NEW_TAG
            git push origin $NEW_TAG


  rollback:
    name: Rollback to last stable version
    if: failure()  # Запускаем откат, если deploy упал
    runs-on: ubuntu-latest
    needs: deploy  # Ждем завершения deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last 2 release tags
        id: get_tags
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USER  }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Получаем два последних релиза
            cd /root/ChatGPT_Telegram_Bot
            git checkout prod
            TAGS=($(git tag --sort=-creatordate | head -2))
            echo "LATEST_TAG=${TAGS[0]}" >> $GITHUB_ENV
            echo "PREV_TAG=${TAGS[1]}" >> $GITHUB_ENV

      - name: Revert to previous release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USER  }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/ChatGPT_Telegram_Bot
            git checkout prod
            git revert -m 1 --no-edit HEAD
            git commit --amend -m "Release $PREV_TAG (Revert $LATEST_TAG) [skip ci]"
            git push origin prod

      - name: Restart Docker Compose on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST  }}
          username: ${{ secrets.SSH_USER  }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e  # Остановка при ошибке
            cd /root/ChatGPT_Telegram_Bot
            git checkout prod

            echo "Pulling latest stable commit from prod"
            git pull origin prod  # Обновляем код после отката

            echo "Stopping running containers"
            docker compose down

            echo "Rebuilding and restarting services"
            docker compose build  # Пересобираем (если Dockerfile изменился)
            docker compose up -d   # Запускаем заново
      