name: Deploy to Server

on:
  push:
    branches:
      - main
  # workflow_dispatch:  # Запуск вручную из GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # --build (it is forced to build the images even when not needed)
          # --remove-orphans (удалить все контейнеры, которые не находятся в конфигурации `compose. yml`)
          # --build (it is forced to build the images even when not needed)
          # --remove-orphans (удалить все контейнеры, которые не находятся в конфигурации `compose. yml`)
          script: |
            cd /root/ChatGPT_Telegram_Bot
            git pull origin main
            docker compose down
            docker compose up --build -d --remove-orphans
            docker compose up --build -d --remove-orphans
            docker image prune -f
            docker volume prune -f
