name: Protect Main Branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - ".github/**"
      - "*.gitignore"
  pull_request:
    branches:
      - main

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure changes are made via Pull Request
        run: |
          if [[ $GITHUB_EVENT_NAME != "pull_request" ]]; then
            echo "Direct push to the main branch is not allowed. Please use a Pull Request."
            exit 1
          fi
